# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 724a166bc6e9127c0cd766f06aaae8d9cf905bc3a41d163d7cf66d244315d3f1051e43a85ceea484af6f1519a4b943cbb78a93573ce186ac7ad0b94e5d68ab9b

test:
  secret_key_base: cd7e7caa25918dbfdf04fd6d5773f515265aa996ad37c8674d1e57d6d48cceb3ff6efbd308d7497ed5e260fdf062a10b75a9b3d60fb858e962310205861a6917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
